{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "afc23c5f_38528032",
        "filename": "src/Subscription.cpp",
        "patchSetId": 3
      },
      "lineNbr": 54,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-10-12T10:19:57Z",
      "side": 1,
      "message": "- this needs a comment why it\u0027s needed (we discussed that on call earlier today)\n- add a test for what happens when the user callback throws",
      "range": {
        "startLine": 50,
        "startChar": 0,
        "endLine": 54,
        "endChar": 5
      },
      "revId": "252a7352a61312969cdbefc034aa3e592a3a01cc",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "188dfb97_fd819c1f",
        "filename": "tests/subscriptions.cpp",
        "patchSetId": 3
      },
      "lineNbr": 137,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2021-10-12T10:19:57Z",
      "side": 1,
      "message": "please also test errors returned from the user CB, and a CB that throws; also any of the three scenarios (OK, error code, exception) should be tested for \"set something\" and \"hasn\u0027t set anything\"",
      "revId": "252a7352a61312969cdbefc034aa3e592a3a01cc",
      "serverId": "e32f8df8-3db0-4f76-a6c6-fe9d6e69dd68"
    }
  ]
}